name: zarinpal
description: Zarinpal Package  for dar & flutter
version: 1.0.4
homepage: https://FlutterFarsi.ir
documentation: https://FlutterFarsi.ir/jalali_calendar.html
repository: https://github.com/irdeveloper89/zarinpal
author: Javad Zobeidi  <j.zobeidi89@gmail.com>

environment:
  sdk: '>=2.12.0 <3.0.0'

dependencies:
  flutter:
    sdk: flutter
  dio: ^4.0.0
  sprintf: ^6.0.0


dev_dependencies:
  flutter_test:
    sdk: flutter

